name: nlp_founder
channels:
- anaconda-fusion
- defaults
dependencies:
- cycler=0.10.0=py36_0
- freetype=2.5.5=2
- icu=54.1=0
- libpng=1.6.27=0
- matplotlib=2.0.2=np112py36_0
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- openssl=1.0.2l=0
- pandas=0.20.1=np112py36_0
- pip=9.0.1=py36_1
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- qt=5.6.2=2
- readline=6.2=2
- requests=2.14.2=py36_0
- scipy=0.19.0=np112py36_0
- seaborn=0.7.1=py36_0
- setuptools=27.2.0=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - asn1crypto==0.22.0
  - beautifulsoup4==4.6.0
  - certifi==2017.4.17
  - cffi==1.10.0
  - chardet==3.0.3
  - cryptography==1.9
  - decorator==4.0.11
  - future==0.16.0
  - idna==2.5
  - ipykernel==4.6.1
  - ipython==6.0.0
  - ipython-genutils==0.2.0
  - jedi==0.10.2
  - jupyter-client==5.0.1
  - jupyter-core==4.3.0
  - keras==2.0.4
  - oauthlib==2.0.2
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.14
  - protobuf==3.3.0
  - ptyprocess==0.5.1
  - pycparser==2.17
  - pygments==2.2.0
  - pyopenssl==17.0.0
  - pysolr==3.6.0
  - python-twitter==3.3
  - pyyaml==3.12
  - pyzmq==16.0.2
  - requests-oauthlib==0.8.0
  - simplegeneric==0.8.1
  - tensorflow==1.1.0
  - theano==0.9.0
  - tornado==4.5.1
  - traitlets==4.3.2
  - tweepy==3.5.0
  - urllib3==1.21.1
  - watson-developer-cloud==0.26.0
  - wcwidth==0.1.7
  - werkzeug==0.12.2
